### ISSUE TITLE
dt_fp = fp_lag * spec_lag

### ISSUE THREAD

**Issue by lvanderlaat** [stanford-futuredata/FAST#17]
Dear FAST developpers:

I am setting up fingerprinting parameters for my channels: ```fp_lag``` and ```spec_lag```. 

I also know that ```dt_fp``` is later required for network detection, and that ```dt_fp = fp_lag * spec_lag```.

But what happens if I set different ```fp_lag``` and ```spec_lag``` for each station? Would this be a problem for network detection? 

I realize that every example provided has the same parameteres in all ```json``` files. So I guess this are not station-channel dependent parameters? Am I right? 

My general question would be, do fingerprint parameters, like `fp_length`, need to be equal at all stations for network detection?  

Thank you very much

Leo

**Comment by kexinrong** [comment]
Hi Leo:

Thanks for reaching out. The current network detection is implemented assuming that `dt_fp` is uniform across stations. It is possible to support different `dt_fp`s, but it would require changing the code. 

In our past experiments, we used the same fingerprints parameters for different stations such that the fingerprints are equally sized and spaced. However, the bandpass filter can be different across stations. You can look at some examples in the parameters/fingerprint folder. 

Kexin

**Comment by lvanderlaat** [comment]
Hi Kexin, 

Thank you for your answer. I'll just copy and paste those parameters.

Leo
