### ISSUE TITLE
sklearn vs. scikit-learn

### ISSUE THREAD

**Issue by dylanmikesell** [stanford-futuredata/FAST#24]
I am attempting to install FAST on a mac. Using anaconda with Python 3.7, I cannot find sklearn. Instead I find scikit-learn. Does pip recognize sklearn? Should this requirement be updated to scikit-learn?

**Comment by kexinrong** [comment]
These two packages should be aliases and they work on my test environments. However, scikit-learn does seem more robust so I will update the requirement to scikit-learn.
