### ISSUE TITLE
"fingerprint.util" import error in run_simsearch.py 

### ISSUE THREAD

**Issue by Da-Been** [stanford-futuredata/FAST#27]
I install and implement the FAST with python2.7 on Ubuntu 18.04.

Trying to run the following command:
$ python run_simsearch.py -c config.json

Encountering the following error:
Traceback (most recent call last):
File "run_simsearch.py", line 5, in <module>
from fingerprint.util import *
ImportError: No module named util

Any ideas how i can solve this problem?
Thank you.

**Comment by andrewtakeshi** [comment]
You can find util.py from this [this commit](https://github.com/stanford-futuredata/FAST/blob/c48b52f7138a62f94c0ce6a480928d0fafac71cd/fingerprint/util.py). Just place it inside the fingerprint folder. I also had the change the import `from feature_extractor import FeatureExtractor` to `from fingerprint.feature_extractor import FeatureExtractor` but I believe that's more to do with Pycharm being weird.

**Comment by kexinrong** [comment]
@andrewtakeshi - Thanks for the comment!
@Da-Been - Sorry for the delay and I have just pushed a commit in master that fixes the import error in run_simsearch.py.
