### ISSUE TITLE
SimilaritySearch.cpp OpenMP Issue

### ISSUE THREAD

**Issue by andrewtakeshi** [stanford-futuredata/FAST#28]
It's possible it's just an issue with my machine, but I wasn't able to get the similarity search to compile without some small modifications. I was getting multiple "<var> not specified in enclosing 'parallel'" errors. I fixed this by declaring the variables as shared, although I believe removing the "default(none)" would have accomplished the same thing. It's been a while since I've used OpenMP though so I'm not 100% sure.

**Comment by davide-piccinini** [comment]
It's the same for me (on Ubuntu 18.04), i get multiple " not specified in enclosing 'parallel'" during  simsearch compilation.

**Comment by davide-piccinini** [comment]
Solved removing default(none) from the code.

**Comment by kexinrong** [comment]
Thank you for your inputs! The compilation works fine on the machines that I've tested, but you are right, removing default(none) works just fine. I pushed a change to master which removes default(none).
