### ISSUE TITLE
Error in execution of run_simsearch.py

### ISSUE THREAD

**Issue by venkat784** [stanford-futuredata/FAST#29]
Dear all I am getting the following error when I execute the  python run_simsearch.py -c config.json command please tell me the solution
Thanking you
 
$python run_simsearch.py -c config.
Traceback (most recent call last):
  File "run_simsearch.py", line 5, in <module>
    from fingerprint.util import *
ModuleNotFoundError: No module named 'fingerprint.util'

**Comment by kexinrong** [comment]
Hi there, this problem should have been fixed in the master branch. Please try pulling the recent commits from master.
